blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Page:index }
    requirements:
         methods:  GET

blog_about:
    path:   /about
    defaults: { _controller: BlogBundle:Page:about }
    requirements:
         methods:  GET

blog_contact:
    path:  /contact
    defaults: { _controller: BlogBundle:Page:contact }
    requirements:
        methods:  GET|POST

blog_login:
    path:   /login
    defaults: { _controller: BlogBundle:Page:login }
    requirements:
         methods:  GET

blog_show:
    path:  /{id}
    defaults: { _controller: BlogBundle:Blog:show }
    requirements:
        methods:  GET
        id: \d+

comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: BlogBundle:Comment:create }
    requirements:
        methods:  POST
        blog_id: \d+



admin_page:
    path: /admin
    defaults: { _controller: BlogBundle:Admin:index }

admin_blog:
    path: /admin/blog/
    defaults: { _controller: BlogBundle:Admin:blog }

admin_blog_edit:
    path: /admin/blog/{id}/edit
    defaults: { _controller: BlogBundle:Admin:blogEdit}
    requirements:
            id: \d+

admin_blog_add:
    path: /admin/blog/add
    defaults: { _controller: BlogBundle:Admin:blogAdd}
